#!/usr/bin/env bash
# Backstage secret loader for the Chunk sidecar demo.
#
# Resolves the demo's tokens from 1Password ONCE and caches them to a
# git-ignored .demo-env at the repo root. After this, ~/.zshrc sources
# .demo-env on every new terminal, so the stage machine never triggers a live
# 1Password / Touch ID prompt mid-demo.
#
#   Backstage, once, with the 1Password app unlocked:
#       ./scripts/demo-env.sh
#
#   Re-run anytime to refresh the tokens. Delete .demo-env to revert to live
#   `op read`s in ~/.zshrc.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CACHE="$REPO_ROOT/.demo-env"

echo "Resolving demo tokens from 1Password (approve the prompt if asked)..."
CIRCLE_TOKEN="$(op read 'op://Private/CircleCI Personal API Token/token')"
ANTHROPIC_API_KEY="$(op read 'op://Customer Engineering/anthropic API KEY /credential')"

if [ -z "${CIRCLE_TOKEN}" ] || [ -z "${ANTHROPIC_API_KEY}" ]; then
  echo "ERROR: a token resolved empty — is the 1Password desktop app unlocked?" >&2
  exit 1
fi

umask 077
cat > "$CACHE" <<EOF
# Generated by scripts/demo-env.sh from 1Password. DO NOT COMMIT.
# Source in any demo terminal:  source .demo-env
export CIRCLE_TOKEN='${CIRCLE_TOKEN}'
export ANTHROPIC_API_KEY='${ANTHROPIC_API_KEY}'
# the DCE-CLI GITHUB_TOKEN is invalid and shadows the gh keychain login; keep it unset
unset GITHUB_TOKEN
EOF
chmod 600 "$CACHE"

echo "Wrote ${CACHE} (chmod 600, git-ignored)."
echo "New terminals will auto-source it; or load it now with:  source .demo-env"
